import 'dart:io';
import 'package:path/path.dart' as p;
import '../registry/registry_manifest.dart';

class BarrelGenerator {
  final String projectRoot;

  BarrelGenerator({required this.projectRoot});

  void regenerate(RegistryManifest manifest, List<String> installedNames) {
    final lines = <String>[
      '// AUTO-GENERATED by flutter_kinetic_ui — do not edit manually',
    ];

    for (final component in manifest.components) {
      if (!installedNames.contains(component.name)) continue;
      for (final file in component.files) {
        lines.add("export '$file';");
      }
    }

    final barrelPath =
        p.join(projectRoot, 'lib', 'kinetic', 'kinetic_ui.dart');
    File(barrelPath).parent.createSync(recursive: true);
    File(barrelPath).writeAsStringSync('${lines.join('\n')}\n');
  }
}
